Improve customsDeclaration for laposte_fr and fix tests
akretion/roulier pull request #135
Opened 2020-12-17 16:15 UTC by christine-ho-dev

2020-12-17 21:02 UTC, florian-dacosta requested changes
Hello, 
First, thanks for the contribution, nice to have contribution on la poste carrier!
I made some comments. Also, it would be nice to make travis green, we use pre-commit to format every thing easily.
To use it, you can install pre-commit : https://pre-commit.com/
Then after cloning the repository you can run `pre-commit install` and the tests will be run automatically on the files you modified, when you commit.

2020-12-17 22:38 UTC, christine-ho-dev commented on roulier/carriers/laposte_fr/api.py
> +                "type": "dict",
I did all my changes according to the newest documentation: https://www.colissimo.entreprise.laposte.fr/system/files/imagescontent/docs/spec_ws_affranchissement.pdf

Though I might have misunderstood how much the schema structure should map to the XML structure so, maybe `category` can remain a simple `integer` while de XML structure has something like 
```
<category><value>3</value></category>
```

2020-12-17 22:51 UTC, christine-ho-dev commented
Thanks for your speedy review and all your feedbacks ! And sorry about the formatting.

I'll try to fix all that tomorrow

2020-12-18 13:06 UTC, christine-ho-dev commented on roulier/carriers/laposte_fr/api.py
> +                            ],
I looked into moving the dependency to `category` but then I can't access the `hsCode` and `originCountry` because they are nested in a list...
So in the end I got rid of both checks as you suggested

2020-12-18 13:36 UTC, florian-dacosta commented
Hello @christine-ho-dev 
So roulier take some input and yes, it is not necessary the same structure or variable names that in documentation.
Indeed, the goal of roulier, is to have one unique api for all carrier, and then roulier transform this generic input into the carrier expected format.

The goal beeing to be able to have a some generic external app for mutliple carriers.
We use this with Odoo ERP and we use multiple carriers (la poste, dpd, gls, geodis, kuehne).
So the external app may always pass the same input dict (street, zipcode, country, etc....) and then roulier transform it depending on the carrier. if for laposte street is actually street1, roulier will adapt it and if for geodis street is actually rue, roulier does the job.
So indeed, there are no relation between the input variable name and what we send to the carrier webservice.

Although some fields are really generic to all carriers (street, etc...) some fields are really specific to a carrier and then maybe we used the same name as the webservice need, I guess it is the case for all cn23 stuff of la poste...Since it is the unique carrier (for now?) that need this, we mostly used the name from la poste but it is not mandatory at all.

So for example :
for hsCode : roulier take "hs" as input : https://github.com/akretion/roulier/blob/master/roulier/carriers/laposte_fr/api.py#L182
But, when adapting to la poste webservice format it put the right name for la poste which is hsCode : https://github.com/akretion/roulier/blob/master/roulier/carriers/laposte_fr/templates/laposte_customsDeclarations.xml#L11

Sale for category, roulier does not take a dict as input, but adapts it to the right format in the xml templates, adding the "value" key : https://github.com/akretion/roulier/blob/master/roulier/carriers/laposte_fr/templates/laposte_customsDeclarations.xml#L16

The main idea of roulier is to have the simplest/common to all carrier api for external apps and that it does all the job of transforming it to the specific carrier format.
There are still a lot of room for improvement of course.

Anyway, thanks for your improvements, IMO that's good. 
Just a breaking change which is the input hs renamed to hsCode, but it is actually better so let's go with it!

If you are not comfortable with pre-commit, black and all this stuff, I can run it to fix the formatting, it is not a problem.
Let me now

2020-12-18 13:37 UTC, florian-dacosta approved these changes

2020-12-18 13:49 UTC, christine-ho-dev commented
Thanks @florian-dacosta for all that extra info, very insightful :) !

2020-12-18 17:07 UTC, christine-ho-dev commented
I just realized I move away the field we actually wanted to add because I though I defined it at the wrong place :facepalm: .

Sorry this PR is not quite ready actually...

2020-12-21 14:11 UTC, christine-ho-dev commented
There, now it should be complete :)

I added more fields and a test where they are all used. 
I ran the tests for both the v1 and v2 APIs of laposte.
Nothing should be breaking.

@florian-dacosta do you want to review it again?

2021-01-01 19:50 UTC, florian-dacosta reviewed
Sorry for the late answer.
I made 2 comments, let me know if you agree
LGTM for the rest

2021-01-01 19:50 UTC, florian-dacosta commented on roulier/carriers/laposte_fr/api.py
> +                    "line0": {
Roulier convert an input dict to the format needed by the carrier webservice, so the input keys don't need to match the carrier webservices keys. In case of laposte, the conversion is done in the xml templates.

For fields really specific to laposte, I guess no probem to put the same name, it is probably easier.
But for fields already used in roulier, I think we should keep a consitency between the names.

So here, it concern an address. Roulier already define an api for addresses and I think we should keep the same names.
Here for exemple : https://github.com/webu/roulier/blob/cn23_customs/roulier/carriers/laposte_fr/api.py#L69
line0, line1, line2 and line3 are called street0, 1, 2, 3.
We should probably call them that here too to keep a consistency.
Same for fields like countrycode, zipcode, etc... : https://github.com/webu/roulier/blob/cn23_customs/roulier/api.py#L86

2021-01-01 19:50 UTC, florian-dacosta commented on roulier/carriers/laposte_fr/templates/laposte_customsDeclarations.xml
> +				{% if customs.original.originalIdent %}
I think you don't really need all these if/endif stuff, because empty tags are automaticallly removed before sending to laposte : https://github.com/webu/roulier/blob/cn23_customs/roulier/carriers/laposte_fr/transport.py#L31

2021-01-04 14:51 UTC, christine-ho-dev commented
@florian-dacosta agreed and fixed :) thanks :+1:

2021-01-06 12:05 UTC, florian-dacosta commented
Thanks, LGTM

2021-01-06 12:05 UTC, merged